version: "3.4"

services:
  frontend:
    container_name: erp_frontend
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - ./:/home/node/app
    command: npm run dev

  router:
    container_name: erp_router
    image: traefik:v2.4.9
    links:
      - frontend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik/rules:/rules
      - ./traefik/accesslog.txt:/accesslog.txt
      - ./traefik/acme.json:/acme.json
    env_file:
      - .env