version: "3.4"

services:
  frontend:
    container_name: erp_frontend
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    command: sh -c "chown -R node:node /home/node/app 2>/dev/null || true && su node -c 'npm install && npm run dev'"

  router:
    container_name: erp_router
    image: traefik:v2.4.9
    links:
      - frontend
    ports:
      - 80:80
      - 443:443
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --log.level=INFO
    volumes:
      - ./traefik/rules:/rules
      - ./traefik/accesslog.txt:/accesslog.txt
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
